# Basic Security Scan with Docker Compose
# Usage: docker-compose -f docker-compose.basic-scan.yml up
version: '3.8'

services:
  security-scanner:
    image: ghcr.io/your-org/security-scanner:latest
    container_name: security-scanner-basic
    volumes:
      # Mount your project directory (read-only)
      - .:/workspace:ro
      # Mount output directory for reports
      - ./security-reports:/app/reports
      # Optional: Mount custom configuration
      - ./config:/app/config:ro
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "
      security-scanner --generate-template basic-scan > /tmp/scan-config.yaml &&
      sed -i 's|git_repositories: \\[\\]|git_repositories: [\"/workspace\"]|g' /tmp/scan-config.yaml &&
      security-scanner /tmp/scan-config.yaml
      "
    networks:
      - security-scan
    restart: "no"

networks:
  security-scan:
    driver: bridge

# Run with: docker-compose -f docker-compose.basic-scan.yml up
# View reports in: ./security-reports/